server:
  port: 8081
spring:
  application:
    name: service-2
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        instance-id: service-2
        service-name: demo-service
        hostname: localhost
        port: ${server.port}
        health-check-url: http://localhost:8081/health
        health-check-interval: 10s
        tags: dev